#!/usr/bin/env bash
# install load balancer

sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 70942-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 70942-web-02 18.204.9.184:80 check\n\tserver 70942-web-01 34.227.92.233:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
